import queue

MyQueue = queue.Queue(3)
print(MyQueue.empty())
print()
input("Press any key when ready...")
MyQueue.put(1)
MyQueue.put(2)
print(MyQueue.full())
print()
input("Press any key when ready...")
MyQueue.put(3)
print(MyQueue.full())
print()
input("Press any key when ready...")
print(MyQueue.get())
print()
print(MyQueue.empty())
print()
print(MyQueue.full())
print()
input("Press any key when ready...")
print(MyQueue.get())
print()
print(MyQueue.get())
print()